const PLACES = [
  {
    "name": "Orrido di Bellano",
    "city": "Bellano",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Natura",
    "status": "Gratis",
    "note": "Ingresso gratuito con Disability Card. Il percorso presenta molte scale e passaggi stretti e non è accessibile con carrozzina.",
    "document": "Disability Card",
    "lat": 46.0432,
    "lon": 9.3021,
    "site": "https://www.orridobellano.eu/it/orari-e-biglietti/",
    "maps": "https://maps.apple.com/?q=Orrido%20di%20Bellano%20Bellano"
  },
  {
    "name": "Museo Giancarlo Vitali",
    "city": "Bellano",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Gratis",
    "note": "Fa parte del circuito culturale di Bellano. Verifica sempre orari e modalità di accesso.",
    "document": "Disability Card",
    "lat": 46.0419,
    "lon": 9.303,
    "site": "https://www.orridobellano.eu/",
    "maps": "https://maps.apple.com/?q=Museo%20Giancarlo%20Vitali%20Bellano"
  },
  {
    "name": "Ca' del Diavol",
    "city": "Bellano",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Gratis",
    "note": "Visita con accessi contingentati; prenotazione consigliata. Verifica l’accessibilità prima della visita.",
    "document": "Disability Card",
    "lat": 46.0431,
    "lon": 9.3018,
    "site": "https://www.orridobellano.eu/it/ca-del-diavol/",
    "maps": "https://maps.apple.com/?q=Ca%27%20del%20Diavol%20Bellano"
  },
  {
    "name": "Villa Monastero",
    "city": "Varenna",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Villa e giardino",
    "status": "Da verificare",
    "note": "Villa storica e giardino botanico sul Lago di Como. Controlla tariffe e accessibilità sul sito ufficiale.",
    "document": "Disability Card",
    "lat": 46.0101,
    "lon": 9.286,
    "site": "https://www.villamonastero.eu/",
    "maps": "https://maps.apple.com/?q=Villa%20Monastero%20Varenna"
  },
  {
    "name": "Castello di Vezio",
    "city": "Perledo",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Castello",
    "status": "Da verificare",
    "note": "Castello panoramico con percorso in salita e terreno irregolare.",
    "document": "Disability Card",
    "lat": 46.0114,
    "lon": 9.2847,
    "site": "https://www.castellodivezio.it/",
    "maps": "https://maps.apple.com/?q=Castello%20di%20Vezio%20Perledo"
  },
  {
    "name": "Lungolago di Varenna",
    "city": "Varenna",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata pubblica sul lago. Alcuni tratti possono avere gradini o pavimentazione irregolare.",
    "document": "Nessun documento",
    "lat": 46.0108,
    "lon": 9.2835,
    "site": "https://www.varennaturismo.com/",
    "maps": "https://maps.apple.com/?q=Lungolago%20di%20Varenna%20Varenna"
  },
  {
    "name": "Piani Resinelli",
    "city": "Abbadia Lariana",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Montagna",
    "status": "Gratis",
    "note": "Località panoramica con sentieri di difficoltà diversa. Verifica il percorso più adatto.",
    "document": "Nessun documento",
    "lat": 45.9062,
    "lon": 9.3949,
    "site": "https://www.pianiresinelli.it/",
    "maps": "https://maps.apple.com/?q=Piani%20Resinelli%20Abbadia%20Lariana"
  },
  {
    "name": "Parco Valentino",
    "city": "Abbadia Lariana",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Parco",
    "status": "Gratis",
    "note": "Area naturale ai Piani Resinelli. I sentieri non sono tutti accessibili.",
    "document": "Nessun documento",
    "lat": 45.9074,
    "lon": 9.3975,
    "site": "https://www.pianiresinelli.it/",
    "maps": "https://maps.apple.com/?q=Parco%20Valentino%20Abbadia%20Lariana"
  },
  {
    "name": "Lungolago di Lecco",
    "city": "Lecco",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata urbana pianeggiante lungo il lago, con bar e servizi nelle vicinanze.",
    "document": "Nessun documento",
    "lat": 45.8557,
    "lon": 9.389,
    "site": "https://leccotourism.it/",
    "maps": "https://maps.apple.com/?q=Lungolago%20di%20Lecco%20Lecco"
  },
  {
    "name": "Palazzo delle Paure",
    "city": "Lecco",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Museo civico nel centro di Lecco. Controlla gratuità, orari e accessibilità.",
    "document": "Disability Card",
    "lat": 45.8565,
    "lon": 9.39,
    "site": "https://leccotourism.it/",
    "maps": "https://maps.apple.com/?q=Palazzo%20delle%20Paure%20Lecco"
  },
  {
    "name": "Museo Manzoniano",
    "city": "Lecco",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Museo dedicato ad Alessandro Manzoni. Verifica tariffe e accessibilità.",
    "document": "Disability Card",
    "lat": 45.8524,
    "lon": 9.3974,
    "site": "https://leccotourism.it/",
    "maps": "https://maps.apple.com/?q=Museo%20Manzoniano%20Lecco"
  },
  {
    "name": "Monte Barro",
    "city": "Galbiate",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Parco naturale",
    "status": "Gratis",
    "note": "Parco regionale con punti panoramici e sentieri. Scegli percorsi compatibili con le tue esigenze.",
    "document": "Nessun documento",
    "lat": 45.8202,
    "lon": 9.3718,
    "site": "https://www.parcomontebarro.it/",
    "maps": "https://maps.apple.com/?q=Monte%20Barro%20Galbiate"
  },
  {
    "name": "Eremo di Monte Barro",
    "city": "Galbiate",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Luogo storico",
    "status": "Da verificare",
    "note": "Complesso storico nel Parco Monte Barro. Verifica apertura, parcheggi e accessibilità.",
    "document": "Disability Card",
    "lat": 45.8191,
    "lon": 9.3763,
    "site": "https://www.parcomontebarro.it/",
    "maps": "https://maps.apple.com/?q=Eremo%20di%20Monte%20Barro%20Galbiate"
  },
  {
    "name": "Lago di Annone",
    "city": "Annone di Brianza",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Lago",
    "status": "Gratis",
    "note": "Area panoramica con tratti di passeggiata e punti di sosta.",
    "document": "Nessun documento",
    "lat": 45.8026,
    "lon": 9.3312,
    "site": "https://leccotourism.it/",
    "maps": "https://maps.apple.com/?q=Lago%20di%20Annone%20Annone%20di%20Brianza"
  },
  {
    "name": "Santuario della Madonna del Bosco",
    "city": "Imbersago",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Luogo di culto",
    "status": "Gratis",
    "note": "Accesso religioso gratuito. Sono presenti scalinate; verifica gli accessi alternativi.",
    "document": "Nessun documento",
    "lat": 45.7094,
    "lon": 9.4452,
    "site": "https://www.madonnadelbosco.org/",
    "maps": "https://maps.apple.com/?q=Santuario%20della%20Madonna%20del%20Bosco%20Imbersago"
  },
  {
    "name": "Traghetto di Leonardo",
    "city": "Imbersago",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Attrazione",
    "status": "Da verificare",
    "note": "Storico traghetto sull’Adda. Servizio soggetto a condizioni del fiume e orari stagionali.",
    "document": "Disability Card",
    "lat": 45.7066,
    "lon": 9.4441,
    "site": "https://www.prolocoimbersago.it/",
    "maps": "https://maps.apple.com/?q=Traghetto%20di%20Leonardo%20Imbersago"
  },
  {
    "name": "Lungofiume Adda",
    "city": "Brivio",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata pubblica lungo l’Adda, generalmente pianeggiante nel tratto centrale.",
    "document": "Nessun documento",
    "lat": 45.7388,
    "lon": 9.4422,
    "site": "https://www.comune.brivio.lc.it/",
    "maps": "https://maps.apple.com/?q=Lungofiume%20Adda%20Brivio"
  },
  {
    "name": "Riserva Lago di Sartirana",
    "city": "Merate",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Riserva naturale",
    "status": "Gratis",
    "note": "Percorso naturalistico attorno al lago. Alcuni tratti possono essere sterrati.",
    "document": "Nessun documento",
    "lat": 45.6967,
    "lon": 9.4085,
    "site": "https://www.comune.merate.lc.it/",
    "maps": "https://maps.apple.com/?q=Riserva%20Lago%20di%20Sartirana%20Merate"
  },
  {
    "name": "Villa Confalonieri",
    "city": "Merate",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Villa e parco",
    "status": "Da verificare",
    "note": "Villa storica e parco comunale. Verifica eventi, aperture e accessibilità.",
    "document": "Disability Card",
    "lat": 45.6989,
    "lon": 9.414,
    "site": "https://www.comune.merate.lc.it/",
    "maps": "https://maps.apple.com/?q=Villa%20Confalonieri%20Merate"
  },
  {
    "name": "Parco Adda Nord",
    "city": "Calusco d'Adda",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Parco naturale",
    "status": "Gratis",
    "note": "Area fluviale con percorsi ciclopedonali. Verifica il fondo e la pendenza del tratto scelto.",
    "document": "Nessun documento",
    "lat": 45.689,
    "lon": 9.4663,
    "site": "https://www.parcoaddanord.it/",
    "maps": "https://maps.apple.com/?q=Parco%20Adda%20Nord%20Calusco%20d%27Adda"
  },
  {
    "name": "Ponte San Michele",
    "city": "Calusco d'Adda",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Monumento",
    "status": "Gratis",
    "note": "Ponte storico visibile da vari punti panoramici lungo l’Adda.",
    "document": "Nessun documento",
    "lat": 45.6812,
    "lon": 9.4676,
    "site": "https://www.parcoaddanord.it/",
    "maps": "https://maps.apple.com/?q=Ponte%20San%20Michele%20Calusco%20d%27Adda"
  },
  {
    "name": "Santuario di Sotto il Monte",
    "city": "Sotto il Monte Giovanni XXIII",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Luogo di culto",
    "status": "Gratis",
    "note": "Accesso religioso gratuito. Verifica orari e accessibilità dei singoli edifici.",
    "document": "Nessun documento",
    "lat": 45.7053,
    "lon": 9.5031,
    "site": "https://www.papagiovanni.com/",
    "maps": "https://maps.apple.com/?q=Santuario%20di%20Sotto%20il%20Monte%20Sotto%20il%20Monte%20Giovanni%20XXIII"
  },
  {
    "name": "Casa Natale di Papa Giovanni XXIII",
    "city": "Sotto il Monte Giovanni XXIII",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Luogo della memoria dedicato a Papa Giovanni XXIII. Verifica modalità di visita.",
    "document": "Disability Card",
    "lat": 45.7043,
    "lon": 9.505,
    "site": "https://www.papagiovanni.com/",
    "maps": "https://maps.apple.com/?q=Casa%20Natale%20di%20Papa%20Giovanni%20XXIII%20Sotto%20il%20Monte%20Giovanni%20XXIII"
  },
  {
    "name": "Parco di Montevecchia e Valle del Curone",
    "city": "Montevecchia",
    "province": "Lecco",
    "region": "Lombardia",
    "type": "Parco naturale",
    "status": "Gratis",
    "note": "Parco con sentieri e punti panoramici. Molti tratti sono in salita o sterrati.",
    "document": "Nessun documento",
    "lat": 45.7042,
    "lon": 9.3784,
    "site": "https://www.parcocurone.it/",
    "maps": "https://maps.apple.com/?q=Parco%20di%20Montevecchia%20e%20Valle%20del%20Curone%20Montevecchia"
  },
  {
    "name": "Città Alta",
    "city": "Bergamo",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Borgo storico",
    "status": "Gratis",
    "note": "Centro storico visitabile liberamente. Attenzione a pavé, pendenze e ZTL.",
    "document": "Nessun documento",
    "lat": 45.704,
    "lon": 9.6624,
    "site": "https://www.visitbergamo.net/",
    "maps": "https://maps.apple.com/?q=Citt%C3%A0%20Alta%20Bergamo"
  },
  {
    "name": "Mura Veneziane",
    "city": "Bergamo",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Monumento",
    "status": "Gratis",
    "note": "Passeggiata panoramica lungo le mura UNESCO. Diversi tratti sono accessibili dalla strada.",
    "document": "Nessun documento",
    "lat": 45.7034,
    "lon": 9.6608,
    "site": "https://www.visitbergamo.net/",
    "maps": "https://maps.apple.com/?q=Mura%20Veneziane%20Bergamo"
  },
  {
    "name": "Accademia Carrara",
    "city": "Bergamo",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Pinacoteca di Bergamo. Controlla gratuità e prenotazione sul sito ufficiale.",
    "document": "Disability Card",
    "lat": 45.7044,
    "lon": 9.6752,
    "site": "https://www.lacarrara.it/",
    "maps": "https://maps.apple.com/?q=Accademia%20Carrara%20Bergamo"
  },
  {
    "name": "Museo di Scienze Naturali Enrico Caffi",
    "city": "Bergamo",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Museo civico in Città Alta. Verifica tariffe e accessibilità.",
    "document": "Disability Card",
    "lat": 45.7068,
    "lon": 9.6582,
    "site": "https://www.museoscienzebergamo.it/",
    "maps": "https://maps.apple.com/?q=Museo%20di%20Scienze%20Naturali%20Enrico%20Caffi%20Bergamo"
  },
  {
    "name": "Crespi d'Adda",
    "city": "Capriate San Gervasio",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Borgo storico",
    "status": "Gratis",
    "note": "Villaggio operaio UNESCO visitabile liberamente all’esterno. Visite guidate e musei hanno tariffe proprie.",
    "document": "Nessun documento",
    "lat": 45.5954,
    "lon": 9.5365,
    "site": "https://www.crespidadda.it/",
    "maps": "https://maps.apple.com/?q=Crespi%20d%27Adda%20Capriate%20San%20Gervasio"
  },
  {
    "name": "Castello di Malpaga",
    "city": "Cavernago",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Castello",
    "status": "Da verificare",
    "note": "Castello storico con visite ed eventi. Verifica tariffe e accessibilità.",
    "document": "Disability Card",
    "lat": 45.625,
    "lon": 9.763,
    "site": "https://www.castellomalpaga.it/",
    "maps": "https://maps.apple.com/?q=Castello%20di%20Malpaga%20Cavernago"
  },
  {
    "name": "San Pellegrino Terme",
    "city": "San Pellegrino Terme",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Borgo e terme",
    "status": "Gratis",
    "note": "Passeggiata nel centro liberty gratuita; terme e visite guidate hanno tariffe proprie.",
    "document": "Nessun documento",
    "lat": 45.838,
    "lon": 9.6646,
    "site": "https://www.visitbergamo.net/",
    "maps": "https://maps.apple.com/?q=San%20Pellegrino%20Terme%20San%20Pellegrino%20Terme"
  },
  {
    "name": "Cascate del Serio",
    "city": "Valbondione",
    "province": "Bergamo",
    "region": "Lombardia",
    "type": "Cascata",
    "status": "Gratis",
    "note": "Visibili solo in specifiche giornate di apertura. Percorso di montagna con dislivello.",
    "document": "Nessun documento",
    "lat": 46.0601,
    "lon": 10.0135,
    "site": "https://www.turismovalseriana.it/",
    "maps": "https://maps.apple.com/?q=Cascate%20del%20Serio%20Valbondione"
  },
  {
    "name": "Lungolago di Como",
    "city": "Como",
    "province": "Como",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata urbana sul lago con tratti pianeggianti.",
    "document": "Nessun documento",
    "lat": 45.8138,
    "lon": 9.0801,
    "site": "https://www.visitcomo.eu/",
    "maps": "https://maps.apple.com/?q=Lungolago%20di%20Como%20Como"
  },
  {
    "name": "Tempio Voltiano",
    "city": "Como",
    "province": "Como",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Museo dedicato ad Alessandro Volta. Controlla tariffe e accessibilità.",
    "document": "Disability Card",
    "lat": 45.8148,
    "lon": 9.0739,
    "site": "https://museicivici.comune.como.it/",
    "maps": "https://maps.apple.com/?q=Tempio%20Voltiano%20Como"
  },
  {
    "name": "Villa Olmo",
    "city": "Como",
    "province": "Como",
    "region": "Lombardia",
    "type": "Villa e parco",
    "status": "Gratis",
    "note": "Parco generalmente accessibile gratuitamente; mostre e interni possono avere tariffe proprie.",
    "document": "Nessun documento",
    "lat": 45.8131,
    "lon": 9.0634,
    "site": "https://www.villaolmocomo.it/",
    "maps": "https://maps.apple.com/?q=Villa%20Olmo%20Como"
  },
  {
    "name": "Funicolare Como-Brunate",
    "city": "Como",
    "province": "Como",
    "region": "Lombardia",
    "type": "Trasporto panoramico",
    "status": "Da verificare",
    "note": "Verifica tariffa, assistenza e accessibilità prima del viaggio.",
    "document": "Disability Card",
    "lat": 45.817,
    "lon": 9.0867,
    "site": "https://www.funicolarecomo.it/",
    "maps": "https://maps.apple.com/?q=Funicolare%20Como-Brunate%20Como"
  },
  {
    "name": "Villa Carlotta",
    "city": "Tremezzina",
    "province": "Como",
    "region": "Lombardia",
    "type": "Villa e giardino",
    "status": "Da verificare",
    "note": "Villa e giardino botanico. Verifica agevolazioni e percorsi accessibili.",
    "document": "Disability Card",
    "lat": 45.9866,
    "lon": 9.2313,
    "site": "https://www.villacarlotta.it/",
    "maps": "https://maps.apple.com/?q=Villa%20Carlotta%20Tremezzina"
  },
  {
    "name": "Giardini di Villa Melzi",
    "city": "Bellagio",
    "province": "Como",
    "region": "Lombardia",
    "type": "Giardino",
    "status": "Da verificare",
    "note": "Giardini storici sul lago. Verifica tariffe, pendenze e accessibilità.",
    "document": "Disability Card",
    "lat": 45.9796,
    "lon": 9.2587,
    "site": "https://www.giardinidivillamelzi.it/",
    "maps": "https://maps.apple.com/?q=Giardini%20di%20Villa%20Melzi%20Bellagio"
  },
  {
    "name": "Lungolago di Bellagio",
    "city": "Bellagio",
    "province": "Como",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata pubblica sul lago; il borgo presenta anche scalinate e vicoli ripidi.",
    "document": "Nessun documento",
    "lat": 45.9876,
    "lon": 9.2614,
    "site": "https://www.bellagiolakecomo.com/",
    "maps": "https://maps.apple.com/?q=Lungolago%20di%20Bellagio%20Bellagio"
  },
  {
    "name": "Orrido di Nesso",
    "city": "Nesso",
    "province": "Como",
    "region": "Lombardia",
    "type": "Natura",
    "status": "Gratis",
    "note": "La vista dal borgo è gratuita. Per raggiungere il ponte e la gola sono presenti molte scale.",
    "document": "Nessun documento",
    "lat": 45.9118,
    "lon": 9.1568,
    "site": "https://www.my-lake-como.com/",
    "maps": "https://maps.apple.com/?q=Orrido%20di%20Nesso%20Nesso"
  },
  {
    "name": "Menaggio lungolago",
    "city": "Menaggio",
    "province": "Como",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata pubblica sul Lago di Como, in buona parte pianeggiante.",
    "document": "Nessun documento",
    "lat": 46.0207,
    "lon": 9.2371,
    "site": "https://menaggio.it/",
    "maps": "https://maps.apple.com/?q=Menaggio%20lungolago%20Menaggio"
  },
  {
    "name": "Pinacoteca di Brera",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Museo statale",
    "status": "Gratis",
    "note": "Ingresso gratuito per le persone con disabilità secondo le condizioni dei musei statali. Verifica prenotazione.",
    "document": "Disability Card o documentazione equivalente",
    "lat": 45.472,
    "lon": 9.1881,
    "site": "https://pinacotecabrera.org/",
    "maps": "https://maps.apple.com/?q=Pinacoteca%20di%20Brera%20Milano"
  },
  {
    "name": "Cenacolo Vinciano",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Museo statale",
    "status": "Gratis",
    "note": "Ingresso gratuito per le persone con disabilità; prenotazione obbligatoria.",
    "document": "Disability Card o documentazione equivalente",
    "lat": 45.4659,
    "lon": 9.1706,
    "site": "https://cenacolovinciano.org/",
    "maps": "https://maps.apple.com/?q=Cenacolo%20Vinciano%20Milano"
  },
  {
    "name": "Castello Sforzesco - Musei",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Museo civico",
    "status": "Gratis",
    "note": "I musei civici di Milano prevedono gratuità per le persone con disabilità. Verifica modalità di accesso.",
    "document": "Disability Card",
    "lat": 45.4705,
    "lon": 9.1793,
    "site": "https://www.milanocastello.it/",
    "maps": "https://maps.apple.com/?q=Castello%20Sforzesco%20-%20Musei%20Milano"
  },
  {
    "name": "Museo del Novecento",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Museo civico",
    "status": "Gratis",
    "note": "Ingresso gratuito per le persone con disabilità secondo le condizioni dei musei civici.",
    "document": "Disability Card",
    "lat": 45.4637,
    "lon": 9.1901,
    "site": "https://www.museodelnovecento.org/",
    "maps": "https://maps.apple.com/?q=Museo%20del%20Novecento%20Milano"
  },
  {
    "name": "Museo di Storia Naturale",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Museo civico",
    "status": "Gratis",
    "note": "Ingresso gratuito per le persone con disabilità secondo le condizioni dei musei civici.",
    "document": "Disability Card",
    "lat": 45.4721,
    "lon": 9.2023,
    "site": "https://museodistorianaturalemilano.it/",
    "maps": "https://maps.apple.com/?q=Museo%20di%20Storia%20Naturale%20Milano"
  },
  {
    "name": "Duomo di Milano",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Monumento",
    "status": "Da verificare",
    "note": "L’accesso per la preghiera è libero; terrazze, museo e visite turistiche hanno regole proprie.",
    "document": "Disability Card",
    "lat": 45.4642,
    "lon": 9.1916,
    "site": "https://www.duomomilano.it/",
    "maps": "https://maps.apple.com/?q=Duomo%20di%20Milano%20Milano"
  },
  {
    "name": "Galleria Vittorio Emanuele II",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Monumento",
    "status": "Gratis",
    "note": "Accesso pubblico gratuito alla galleria commerciale.",
    "document": "Nessun documento",
    "lat": 45.4659,
    "lon": 9.19,
    "site": "https://www.yesmilano.it/",
    "maps": "https://maps.apple.com/?q=Galleria%20Vittorio%20Emanuele%20II%20Milano"
  },
  {
    "name": "Parco Sempione",
    "city": "Milano",
    "province": "Milano",
    "region": "Lombardia",
    "type": "Parco",
    "status": "Gratis",
    "note": "Grande parco pubblico nel centro di Milano con viali principali accessibili.",
    "document": "Nessun documento",
    "lat": 45.4734,
    "lon": 9.1764,
    "site": "https://www.comune.milano.it/",
    "maps": "https://maps.apple.com/?q=Parco%20Sempione%20Milano"
  },
  {
    "name": "Villa Reale di Monza",
    "city": "Monza",
    "province": "Monza e Brianza",
    "region": "Lombardia",
    "type": "Villa e museo",
    "status": "Da verificare",
    "note": "Reggia storica con mostre e visite. Verifica tariffe e percorsi accessibili.",
    "document": "Disability Card",
    "lat": 45.5931,
    "lon": 9.2732,
    "site": "https://reggiadimonza.it/",
    "maps": "https://maps.apple.com/?q=Villa%20Reale%20di%20Monza%20Monza"
  },
  {
    "name": "Parco di Monza",
    "city": "Monza",
    "province": "Monza e Brianza",
    "region": "Lombardia",
    "type": "Parco",
    "status": "Gratis",
    "note": "Grande parco pubblico con viali asfaltati e percorsi di varia lunghezza.",
    "document": "Nessun documento",
    "lat": 45.6103,
    "lon": 9.2788,
    "site": "https://www.reggiadimonza.it/",
    "maps": "https://maps.apple.com/?q=Parco%20di%20Monza%20Monza"
  },
  {
    "name": "Autodromo Nazionale Monza",
    "city": "Monza",
    "province": "Monza e Brianza",
    "region": "Lombardia",
    "type": "Attrazione",
    "status": "Da verificare",
    "note": "Accesso e tariffe dipendono dall’evento. Verifica sempre sul sito ufficiale.",
    "document": "Disability Card",
    "lat": 45.6156,
    "lon": 9.281,
    "site": "https://www.monzanet.it/",
    "maps": "https://maps.apple.com/?q=Autodromo%20Nazionale%20Monza%20Monza"
  },
  {
    "name": "Museo di Santa Giulia",
    "city": "Brescia",
    "province": "Brescia",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Museo e sito UNESCO. Verifica gratuità e accessibilità.",
    "document": "Disability Card",
    "lat": 45.5386,
    "lon": 10.2297,
    "site": "https://www.bresciamusei.com/",
    "maps": "https://maps.apple.com/?q=Museo%20di%20Santa%20Giulia%20Brescia"
  },
  {
    "name": "Castello di Brescia",
    "city": "Brescia",
    "province": "Brescia",
    "region": "Lombardia",
    "type": "Castello",
    "status": "Gratis",
    "note": "Accesso esterno e parco gratuiti; musei interni con tariffe proprie. Percorso in salita.",
    "document": "Nessun documento",
    "lat": 45.5439,
    "lon": 10.2252,
    "site": "https://www.bresciamusei.com/",
    "maps": "https://maps.apple.com/?q=Castello%20di%20Brescia%20Brescia"
  },
  {
    "name": "Vittoriale degli Italiani",
    "city": "Gardone Riviera",
    "province": "Brescia",
    "region": "Lombardia",
    "type": "Museo e parco",
    "status": "Da verificare",
    "note": "Complesso museale con parco in pendenza. Verifica agevolazioni e itinerari accessibili.",
    "document": "Disability Card",
    "lat": 45.6232,
    "lon": 10.5624,
    "site": "https://www.vittoriale.it/",
    "maps": "https://maps.apple.com/?q=Vittoriale%20degli%20Italiani%20Gardone%20Riviera"
  },
  {
    "name": "Lungolago di Sirmione",
    "city": "Sirmione",
    "province": "Brescia",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Centro storico e lungolago visitabili liberamente; presenti pavé, folla e ZTL.",
    "document": "Nessun documento",
    "lat": 45.4925,
    "lon": 10.608,
    "site": "https://visitsirmione.com/",
    "maps": "https://maps.apple.com/?q=Lungolago%20di%20Sirmione%20Sirmione"
  },
  {
    "name": "Grotte di Catullo",
    "city": "Sirmione",
    "province": "Brescia",
    "region": "Lombardia",
    "type": "Sito archeologico statale",
    "status": "Gratis",
    "note": "Ingresso gratuito per le persone con disabilità secondo le condizioni dei musei statali. Percorso esterno irregolare.",
    "document": "Disability Card o documentazione equivalente",
    "lat": 45.4991,
    "lon": 10.6083,
    "site": "https://museilombardia.cultura.gov.it/musei/grotte-di-catullo-e-museo-archeologico-di-sirmione/",
    "maps": "https://maps.apple.com/?q=Grotte%20di%20Catullo%20Sirmione"
  },
  {
    "name": "Lungolago di Iseo",
    "city": "Iseo",
    "province": "Brescia",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata pubblica sul lago, generalmente pianeggiante.",
    "document": "Nessun documento",
    "lat": 45.6584,
    "lon": 10.0507,
    "site": "https://visitlakeiseo.info/",
    "maps": "https://maps.apple.com/?q=Lungolago%20di%20Iseo%20Iseo"
  },
  {
    "name": "Monte Isola",
    "city": "Monte Isola",
    "province": "Brescia",
    "region": "Lombardia",
    "type": "Isola e borgo",
    "status": "Gratis",
    "note": "Accesso all’isola libero; traghetto a pagamento. Verifica agevolazioni di navigazione e pendenze.",
    "document": "Disability Card",
    "lat": 45.7141,
    "lon": 10.0804,
    "site": "https://visitlakeiseo.info/",
    "maps": "https://maps.apple.com/?q=Monte%20Isola%20Monte%20Isola"
  },
  {
    "name": "Sacro Monte di Varese",
    "city": "Varese",
    "province": "Varese",
    "region": "Lombardia",
    "type": "Sito religioso",
    "status": "Gratis",
    "note": "Borgo e santuario accessibili liberamente; il percorso delle cappelle è in forte salita.",
    "document": "Nessun documento",
    "lat": 45.8567,
    "lon": 8.7934,
    "site": "https://www.sacromontedivarese.it/",
    "maps": "https://maps.apple.com/?q=Sacro%20Monte%20di%20Varese%20Varese"
  },
  {
    "name": "Giardini Estensi",
    "city": "Varese",
    "province": "Varese",
    "region": "Lombardia",
    "type": "Parco",
    "status": "Gratis",
    "note": "Giardini pubblici nel centro di Varese.",
    "document": "Nessun documento",
    "lat": 45.8183,
    "lon": 8.8265,
    "site": "https://www.comune.varese.it/",
    "maps": "https://maps.apple.com/?q=Giardini%20Estensi%20Varese"
  },
  {
    "name": "Eremo di Santa Caterina del Sasso",
    "city": "Leggiuno",
    "province": "Varese",
    "region": "Lombardia",
    "type": "Luogo religioso",
    "status": "Da verificare",
    "note": "Eremo sul Lago Maggiore. È presente un ascensore, ma verifica funzionamento e accessibilità completa.",
    "document": "Disability Card",
    "lat": 45.8903,
    "lon": 8.5981,
    "site": "https://www.santacaterinadelsasso.com/",
    "maps": "https://maps.apple.com/?q=Eremo%20di%20Santa%20Caterina%20del%20Sasso%20Leggiuno"
  },
  {
    "name": "Lungolago di Luino",
    "city": "Luino",
    "province": "Varese",
    "region": "Lombardia",
    "type": "Passeggiata",
    "status": "Gratis",
    "note": "Passeggiata pubblica sul Lago Maggiore.",
    "document": "Nessun documento",
    "lat": 46.0024,
    "lon": 8.7429,
    "site": "https://www.varesedoyoulake.it/",
    "maps": "https://maps.apple.com/?q=Lungolago%20di%20Luino%20Luino"
  },
  {
    "name": "Ponte nel Cielo",
    "city": "Tartano",
    "province": "Sondrio",
    "region": "Lombardia",
    "type": "Attrazione",
    "status": "Da verificare",
    "note": "Ponte sospeso in montagna; percorso con pendenze e fondo non uniforme.",
    "document": "Disability Card",
    "lat": 46.1069,
    "lon": 9.6781,
    "site": "https://www.pontenelcielo.it/",
    "maps": "https://maps.apple.com/?q=Ponte%20nel%20Cielo%20Tartano"
  },
  {
    "name": "Tirano centro storico",
    "city": "Tirano",
    "province": "Sondrio",
    "region": "Lombardia",
    "type": "Borgo storico",
    "status": "Gratis",
    "note": "Centro storico e santuario visitabili liberamente; il Trenino del Bernina ha tariffe proprie.",
    "document": "Nessun documento",
    "lat": 46.2154,
    "lon": 10.1667,
    "site": "https://www.valtellina.it/",
    "maps": "https://maps.apple.com/?q=Tirano%20centro%20storico%20Tirano"
  },
  {
    "name": "Palazzo Vertemate Franchi",
    "city": "Piuro",
    "province": "Sondrio",
    "region": "Lombardia",
    "type": "Palazzo storico",
    "status": "Da verificare",
    "note": "Palazzo storico della Valchiavenna. Verifica apertura e accessibilità.",
    "document": "Disability Card",
    "lat": 46.331,
    "lon": 9.4207,
    "site": "https://www.valchiavenna.com/",
    "maps": "https://maps.apple.com/?q=Palazzo%20Vertemate%20Franchi%20Piuro"
  },
  {
    "name": "Certosa di Pavia",
    "city": "Certosa di Pavia",
    "province": "Pavia",
    "region": "Lombardia",
    "type": "Luogo religioso",
    "status": "Gratis",
    "note": "Accesso religioso gratuito; verifica orari e accessibilità degli spazi visitabili.",
    "document": "Nessun documento",
    "lat": 45.2563,
    "lon": 9.1449,
    "site": "https://www.certosadipavia.com/",
    "maps": "https://maps.apple.com/?q=Certosa%20di%20Pavia%20Certosa%20di%20Pavia"
  },
  {
    "name": "Castello Visconteo e Musei Civici",
    "city": "Pavia",
    "province": "Pavia",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Musei civici di Pavia. Verifica tariffe e accessibilità.",
    "document": "Disability Card",
    "lat": 45.191,
    "lon": 9.1568,
    "site": "https://museicivici.comune.pv.it/",
    "maps": "https://maps.apple.com/?q=Castello%20Visconteo%20e%20Musei%20Civici%20Pavia"
  },
  {
    "name": "Palazzo Te",
    "city": "Mantova",
    "province": "Mantova",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Museo civico e villa rinascimentale. Verifica gratuità e accessibilità.",
    "document": "Disability Card",
    "lat": 45.1472,
    "lon": 10.786,
    "site": "https://www.centropalazzote.it/",
    "maps": "https://maps.apple.com/?q=Palazzo%20Te%20Mantova"
  },
  {
    "name": "Palazzo Ducale di Mantova",
    "city": "Mantova",
    "province": "Mantova",
    "region": "Lombardia",
    "type": "Museo statale",
    "status": "Gratis",
    "note": "Ingresso gratuito per le persone con disabilità secondo le condizioni dei musei statali.",
    "document": "Disability Card o documentazione equivalente",
    "lat": 45.1608,
    "lon": 10.7977,
    "site": "https://mantovaducale.beniculturali.it/",
    "maps": "https://maps.apple.com/?q=Palazzo%20Ducale%20di%20Mantova%20Mantova"
  },
  {
    "name": "Museo del Violino",
    "city": "Cremona",
    "province": "Cremona",
    "region": "Lombardia",
    "type": "Museo",
    "status": "Da verificare",
    "note": "Museo dedicato alla liuteria. Verifica tariffe e accessibilità.",
    "document": "Disability Card",
    "lat": 45.1337,
    "lon": 10.0214,
    "site": "https://www.museodelviolino.org/",
    "maps": "https://maps.apple.com/?q=Museo%20del%20Violino%20Cremona"
  },
  {
    "name": "Piazza del Comune",
    "city": "Cremona",
    "province": "Cremona",
    "region": "Lombardia",
    "type": "Centro storico",
    "status": "Gratis",
    "note": "Piazza monumentale visitabile liberamente.",
    "document": "Nessun documento",
    "lat": 45.1334,
    "lon": 10.022,
    "site": "https://www.turismocremona.it/",
    "maps": "https://maps.apple.com/?q=Piazza%20del%20Comune%20Cremona"
  },
  {
    "name": "Tempio Civico dell'Incoronata",
    "city": "Lodi",
    "province": "Lodi",
    "region": "Lombardia",
    "type": "Luogo religioso",
    "status": "Da verificare",
    "note": "Edificio rinascimentale nel centro di Lodi. Verifica orari e modalità di visita.",
    "document": "Disability Card",
    "lat": 45.3144,
    "lon": 9.5037,
    "site": "https://www.comune.lodi.it/",
    "maps": "https://maps.apple.com/?q=Tempio%20Civico%20dell%27Incoronata%20Lodi"
  },
  {
    "name": "Piazza della Vittoria",
    "city": "Lodi",
    "province": "Lodi",
    "region": "Lombardia",
    "type": "Centro storico",
    "status": "Gratis",
    "note": "Piazza centrale visitabile liberamente, con pavimentazione in parte irregolare.",
    "document": "Nessun documento",
    "lat": 45.3143,
    "lon": 9.503,
    "site": "https://www.comune.lodi.it/",
    "maps": "https://maps.apple.com/?q=Piazza%20della%20Vittoria%20Lodi"
  }
];
